import type { Metadata } from "next"

export const rootMetadata: Metadata = {
  title: {
    default: "Muhammad Asif - Software Engineer",
    template: "%s | Muhammad Asif",
  },
  description:
    "Seasoned Mid Level Frontend Developer with 4+ years of expertise in crafting responsive, high-performance web applications. Proficient in React, TypeScript, and modern CSS frameworks, with a strong focus on accessibility, UX optimization, scalable architecture, and effective problem solving. Spearheaded a project that improved load times by 40%, resulting in a 25% increase in user engagement. Skilled in mentoring junior developers and working with cross-functional teams to deliver innovative solutions.",
  keywords: [
    "frontend developer",
    "React developer",
    "Next.js developer",
    "JavaScript developer",
    "TypeScript developer",
    "full-stack developer",
    "web developer portfolio",
    "React.js expert",
    "Next.js specialist",
    "responsive web design",
    "REST API development",
    "GraphQL developer",
    "AWS developer",
    "Docker DevOps",
    "UI/UX development",
    "performance optimization",
    "web applications",
    "software engineer",
    "Md. Asif portfolio",
    "freelance developer",
    "web development services",
    "custom web solutions",
    "SPA development",
    "component development",
    "API integration",
    "Agile development",
    "Scrum methodologies",
    "CI/CD implementation",
    "JavaScript ES6+",
    "CSS-in-JS solutions",
    "Tailwind CSS",
    "responsive design",
    "mobile-first development",
    "web performance",
    "SEO optimization",
    "accessibility (a11y)",
    "user experience design",
    "interactive web design",
    "animation development",
    "GSAP animations",
    "state management",
    "data structures",
    "algorithm design",
    "technical leadership",
    "code quality",
    "debugging expertise",
    "problem solving",
    "innovative solutions",
    "tech community",
    "open source contributions",
  ],
  authors: [{ name: "Md. Asif" }],
  creator: "Md. Asif",
  publisher: "Md. Asif",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://muhammadasif.me",
    title: "Muhammad Asif - Software Engineer",
    description:
      "Seasoned Mid Level Frontend Developer with 4+ years of expertise in crafting responsive, high-performance web applications.",
    siteName: "Md. Asif - Portfolio",
    images: [
      {
        url: "https://muhammadasif.me/images/muhammadasif-me.webp",
        width: 1200,
        height: 630,
        alt: "Muhammad Asif - Software Engineer",
        type: "image/webp",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Muhammad Asif - Software Engineer",
    description:
      "Seasoned Mid Level Frontend Developer focused on performance and UX.",
    creator: "@mdasif-me",
    images: ["https://muhammadasif.me/images/muhammadasif-me.webp"],
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: "https://muhammadasif.me",
    languages: {
      "en-US": "https://muhammadasif.me",
    },
  },
}

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
}
